id = "sammcj.ollama-modelfile"
name = "Ollama Modelfile"
version = "0.1.0"
schema_version = 1
authors = ["Sam McLeod"]
description = "Ollama Modelfile support for Zed"
commit = "9d0fa1057a01e07c455423c0cbba1913d0def2ac"

[grammars.ollama_modelfile]
repository = "https://github.com/sammcj/zed-plugin-ollama-modelfile"
commit = "9d0fa1057a01e07c455423c0cbba1913d0def2ac"
path = "."
