id = "sammcj.ollama-modelfile"
name = "Ollama Modelfile"
version = "0.1.0"
schema_version = 1
authors = ["Sam McLeod"]
description = "Ollama Modelfile support for Zed"
commit = "10b005ce1846cc017a4faa7cfef36200e64d2b8c"

[grammars.ollama_modelfile]
repository = "https://github.com/sammcj/zed-plugin-ollama-modelfile"
commit = "10b005ce1846cc017a4faa7cfef36200e64d2b8c"
path = "."
