id = "sammcj.ollama-modelfile"
name = "Ollama Modelfile"
version = "0.1.0"
schema_version = 1
authors = ["Sam McLeod <sam.mcleod@zed.dev>"]
description = "Ollama Modelfile support for Zed"
repository = "https://github.com/sammcj/zed-plugin-ollama-modelfile"

[grammars.ollama-modelfile]
repository = "https://github.com/sammcj/zed-plugin-ollama-modelfile"
commit = "4a1bb26c3f5fb5b46d8881cb6901d49a9e23cc07"
